name: TriFectaSettings
options:
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ""
packages:
  Yams:
    path: Deps/Yams
targets:
  TriFectaSettingsCore:
    type: library.static
    platform: macOS
    sources:
      - Sources/TriFectaSettingsCore
    dependencies:
      - package: Yams
    settings:
      base:
        SKIP_INSTALL: "YES"
  TriFectaSettings:
    type: application
    platform: macOS
    sources:
      - Sources/TriFectaSettings
    dependencies:
      - target: TriFectaSettingsCore
      - package: Yams
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: im.rime.inputmethod.Squirrel.settings
        INFOPLIST_FILE: "Sources/TriFectaSettings/Resources/Info.plist"
        GENERATE_INFOPLIST_FILE: "NO"
        ENABLE_HARDENED_RUNTIME: "NO"
        CODE_SIGN_IDENTITY: "-"
schemes:
  TriFectaSettings:
    build:
      targets:
        TriFectaSettings: all
    run:
      config: Debug
